//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RotatedViews.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UIStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RotatedViews.Resources.UIStrings", typeof(UIStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        public static string AdvancedTabLabel {
            get {
                return ResourceManager.GetString("AdvancedTabLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle between.
        /// </summary>
        public static string AngleBetweenLabel {
            get {
                return ResourceManager.GetString("AngleBetweenLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle:.
        /// </summary>
        public static string AngleLabel {
            get {
                return ResourceManager.GetString("AngleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply the current rotation.
        /// </summary>
        public static string ApplyToolTipBody {
            get {
                return ResourceManager.GetString("ApplyToolTipBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string ApplyToolTipTitle {
            get {
                return ResourceManager.GetString("ApplyToolTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic.
        /// </summary>
        public static string BasicTabLabel {
            get {
                return ResourceManager.GetString("BasicTabLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Rotate View.
        /// </summary>
        public static string CloseToolTipBody {
            get {
                return ResourceManager.GetString("CloseToolTipBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CloseToolTipTitle {
            get {
                return ResourceManager.GetString("CloseToolTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance:.
        /// </summary>
        public static string DistanceLabel {
            get {
                return ResourceManager.GetString("DistanceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle must be a number.
        /// </summary>
        public static string DoubleRuleLabel {
            get {
                return ResourceManager.GetString("DoubleRuleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instances.
        /// </summary>
        public static string InstancesLabel {
            get {
                return ResourceManager.GetString("InstancesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number:.
        /// </summary>
        public static string NumberLabel {
            get {
                return ResourceManager.GetString("NumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply the current rotation and close Rotate View.
        /// </summary>
        public static string OkToolTipBody {
            get {
                return ResourceManager.GetString("OkToolTipBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string OkToolTipTitle {
            get {
                return ResourceManager.GetString("OkToolTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number must be a positive integer.
        /// </summary>
        public static string PositiveIntegerRuleLabel {
            get {
                return ResourceManager.GetString("PositiveIntegerRuleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset to default.
        /// </summary>
        public static string ResetToDefaultHeader {
            get {
                return ResourceManager.GetString("ResetToDefaultHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotation Axis:.
        /// </summary>
        public static string RotationAxisLabel {
            get {
                return ResourceManager.GetString("RotationAxisLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.
        /// </summary>
        public static string RotationAxisXLabel {
            get {
                return ResourceManager.GetString("RotationAxisXLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y.
        /// </summary>
        public static string RotationAxisYLabel {
            get {
                return ResourceManager.GetString("RotationAxisYLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z.
        /// </summary>
        public static string RotationAxisZLabel {
            get {
                return ResourceManager.GetString("RotationAxisZLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as default.
        /// </summary>
        public static string SaveAsDefaultHeader {
            get {
                return ResourceManager.GetString("SaveAsDefaultHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsLabel {
            get {
                return ResourceManager.GetString("SettingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source View.
        /// </summary>
        public static string SourceViewLabel {
            get {
                return ResourceManager.GetString("SourceViewLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate View.
        /// </summary>
        public static string TitleLabel {
            get {
                return ResourceManager.GetString("TitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total sweep.
        /// </summary>
        public static string TotalSweepLabel {
            get {
                return ResourceManager.GetString("TotalSweepLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Name Template.
        /// </summary>
        public static string ViewNameLabel {
            get {
                return ResourceManager.GetString("ViewNameLabel", resourceCulture);
            }
        }
    }
}
